### ISSUE TITLE
打开超慢

### ISSUE THREAD

**Issue by zcoding** [museui/museui.github.io#1]
<img width="1279" alt="shit2" src="https://cloud.githubusercontent.com/assets/4773646/21313361/73b5c9aa-c62c-11e6-88fa-fb2582986ca7.png">

如图，跑了一分钟。

一分钟啊！

**Comment by myronliu347** [comment]
这是个纯静态页面，没有做过任何网络请求方面的优化，再加上github在国内的访问速度确实不快，所以首次加载比较慢
