### ISSUE TITLE
404 Error when visiting documentation for v2.10.0

### ISSUE THREAD

**Issue by rocka** [museui/museui.github.io#4]
At present, documentation for v2.10.0 is linked to https://muse-ui.org/2.1.0/

![image](https://user-images.githubusercontent.com/13914967/42737003-cc070810-88a1-11e8-8b72-226bfd353e29.png)

but when visiting that link, GitHub shows a 404 Error

![image](https://user-images.githubusercontent.com/13914967/42736990-8dde113c-88a1-11e8-985c-3763e78956cc.png)

**Comment by myronliu347** [comment]
Is ok  right now
